import './globals.css';
import type { Metadata } from 'next';
import * as React from 'react';
import localFont from 'next/font/local';
import Provider from '@/lib/provider';
import MIReactNodeProvider from '@/lib/mi-react-node-provider';
import StyledComponentsRegistry from '@/lib/registry';
import {ToastRoot} from "@kiwicom/orbit-components";
import Button from "@kiwicom/orbit-components/lib/Button";

const circularXX = localFont({
  src: [
    {
      path: '../public/fonts/CircularXX-Thin.otf',
      weight: '100',
      style: 'normal',
    },
    {
      path: '../public/fonts/CircularXX-ThinItalic.otf',
      weight: '100',
      style: 'italic',
    },
    {
      path: '../public/fonts/CircularXX-Light.otf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../public/fonts/CircularXX-LightItalic.otf',
      weight: '300',
      style: 'italic',
    },
    {
      path: '../public/fonts/CircularXX-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/CircularXX-Italic.otf',
      weight: '400',
      style: 'italic',
    },
    {
      path: '../public/fonts/CircularXX-Book.otf',
      weight: '450',
      style: 'normal',
    },
    {
      path: '../public/fonts/CircularXX-BookItalic.otf',
      weight: '450',
      style: 'italic',
    },
    {
      path: '../public/fonts/CircularXX-Medium.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../public/fonts/CircularXX-MediumItalic.otf',
      weight: '500',
      style: 'italic',
    },
    {
      path: '../public/fonts/CircularXX-Bold.otf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../public/fonts/CircularXX-BoldItalic.otf',
      weight: '700',
      style: 'italic',
    },
    {
      path: '../public/fonts/CircularXX-Black.otf',
      weight: '900',
      style: 'normal',
    },
    {
      path: '../public/fonts/CircularXX-BlackItalic.otf',
      weight: '900',
      style: 'italic',
    },
    {
      path: '../public/fonts/CircularXX-ExtraBlack.otf',
      weight: '950',
      style: 'normal',
    },
    {
      path: '../public/fonts/CircularXX-ExtraBlackItalic.otf',
      weight: '950',
      style: 'italic',
    },
  ],
  variable: '--font-base',
});

export const metadata: Metadata = {
  title: 'Kiwi Blank Codebase',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={circularXX.className}>
        <img
          src="https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=200&h=200&fit=crop"
          alt="Decorative overlay"
          className="fixed top-4 right-4 w-24 h-24 rounded-xl shadow-lg object-cover z-50 border-2 border-white"
        />
        <Button type="secondary" size="large">
          Explore Features
        </Button>
        <Provider>
          <MIReactNodeProvider>
            <StyledComponentsRegistry>
              <div className="relative min-h-screen">
                {children}
                <svg
                  className="fixed inset-0 w-full h-full pointer-events-none z-50"
                  xmlns="http://www.w3.org/2000/svg"
                  preserveAspectRatio="none"
                >
                  <defs>
                    <pattern id="grid-pattern" width="40" height="40" patternUnits="userSpaceOnUse">
                      <path d="M 40 0 L 0 0 0 40" fill="none" stroke="rgba(99, 102, 241, 0.08)" strokeWidth="1"/>
                    </pattern>
                  </defs>
                  <rect width="100%" height="100%" fill="url(#grid-pattern)" />
                </svg>
              </div>
            </StyledComponentsRegistry>
            <ToastRoot />
          </MIReactNodeProvider>
        </Provider>
      </body>
    </html>
  );
}
