import './globals.css';
import type { Metadata } from 'next';
import * as React from 'react';
import { Roboto } from 'next/font/google';
import Provider from '@/lib/provider';
import MIReactNodeProvider from '@/lib/mi-react-node-provider';
import StyledComponentsRegistry from '@/lib/registry';
import {ToastRoot} from "@kiwicom/orbit-components";

const roboto = Roboto({ weight: '400', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Kiwi Blank Codebase',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
      <Provider>
        <MIReactNodeProvider>
          <StyledComponentsRegistry>
            {children}
          </StyledComponentsRegistry>
          <ToastRoot />
        </MIReactNodeProvider>
      </Provider>
      </body>
    </html>
  );
}
